// ─────────────────────────────────────────────────────────────────────────────
//  SOLE STYLE — Scraped from Itsu.ma (Authentic Catalog)
// ─────────────────────────────────────────────────────────────────────────────

const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();

const User = require("./models/User");
const Category = require("./models/Category");
const Product = require("./models/Product");

const MONGO_URI = process.env.MONGODB_URI || process.env.MONGO_URI || "mongodb://localhost:27017/solestyle";

const categories = [
  { name: "Sneakers", slug: "sneakers", emoji: "👟", description: "Baskets Premium", order: 1 },
  { name: "Sandales", slug: "sandales", emoji: "🩴", description: "Slides & Sandals", order: 2 }
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ MongoDB connecté");

    await Promise.all([
      Product.deleteMany({}),
      Category.deleteMany({}),
    ]);
    console.log("🧹 Collections nettoyées");

    const createdCategories = await Category.insertMany(categories);
    const catMap = {};
    createdCategories.forEach((c) => (catMap[c.slug] = c._id));
    console.log(`📂 ${createdCategories.length} catégories créées`);

    const products = [
      {
        name: "Nike V2K Run Platinum Tint",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 640,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_v2k_run_platinum_tint.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike V5 RNR Psychic Blue",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 660,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_v5_rnr_psychic_blue.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike V2K Run Pure Platinum Metallic Silver",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 650,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_v2k_run_pure_platinum_metallic_silver.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike V2K Run Summery Florals",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_v2k_run_summery_florals.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike V5 RNR Sail Fauna Brown",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 660,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_v5_rnr_sail_fauna_brown.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Vans knu skool Bleu Roi Rose",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 660,
        category: catMap["sneakers"],
        brand: "Vans",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_vans_knu_skool_bleu_roi_rose.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike Air Zoom Alphafly NEXT% 2 Total Orange",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 650,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_zoom_alphafly_next__2_total_orange.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike ZoomX Invincible Run Flyknit 3 White Cobalt Bliss",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_zoomx_invincible_run_flyknit_3_white_cobalt_bliss.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "ON Cloudsolo x Loewe White Light Grey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 730,
        category: catMap["sneakers"],
        brand: "On",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_on_cloudsolo_x_loewe_white_light_grey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "On Cloudsurfer on Glacier",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 640,
        category: catMap["sneakers"],
        brand: "On",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_on_cloudsurfer_on_glacier.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike ZoomX Invincible Run Flyknit 3 White Bright Crimson",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_zoomx_invincible_run_flyknit_3_white_bright_crimson.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "New Balance Fresh Foam X More Trail v3 Black Cayenne",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_fresh_foam_x_more_trail_v3_black_cayenne.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Asics Gel NYC Cream Cloud Grey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 760,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_nyc_cream_cloud_grey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike Air Zoom Vomero 5 Platinum Violet Gold",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_zoom_vomero_5_platinum_violet_gold.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Adidas Handball Spezial Scarlet Gum",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 640,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_handball_spezial_scarlet_gum.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: true,
      },
      {
        name: "Nike Air Max 95 Recraft GS Triple Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 590,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_max_95_recraft_gs_triple_black.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Covnerse Run Star Motion White Gum Honey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Converse",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_covnerse_run_star_motion_white_gum_honey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 x Fragment Design x Travis Scott Retro Low OG SP Sail Military Blue",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_x_fragment_design_x_travis_scott_retro_low_og_sp_sail_military_blue.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Low Shadow Brown",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_low_shadow_brown.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Low Sail Soft Pearl Sequins",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_low_sail_soft_pearl_sequins.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Mid Digital Pink",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 640,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_mid_digital_pink.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Cactus Jack Travis Scott",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 660,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_cactus_jack_travis_scott.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Retro High OG Hyper Royal",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 670,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_retro_high_og_hyper_royal.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance 9060 Black Slate Grey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 740,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_9060_black_slate_grey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance x Miu Miu 530 SL Ecru",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 710,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_x_miu_miu_530_sl_ecru.png"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance x Miu Miu 530 SL Cinnamon",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 720,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_x_miu_miu_530_sl_cinnamon.png"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance 9060 Quartz Grey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 750,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_9060_quartz_grey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance 530 Dark Mushroom incense",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 660,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_530_dark_mushroom_incense.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance 9060 x Joe Freshgoods Dark Gray",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 740,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_9060_x_joe_freshgoods_dark_gray.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel Kayano 14 Silver Grape",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_kayano_14_silver_grape.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel NYC Moss",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 690,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_nyc_moss.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel Kayano 31 Black White",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 650,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_kayano_31_black_white.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel Kayano 14 Pure Silver Slate Grey",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 740,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_kayano_14_pure_silver_slate_grey.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel Kayano 31 Lite Show Digital Aqua",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 690,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_kayano_31_lite_show_digital_aqua.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Asics Gel Quantum Kinetic Carbon Pure Gol",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 650,
        category: catMap["sneakers"],
        brand: "Asics",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_asics_gel_quantum_kinetic_carbon_pure_gol.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Samba OG White Halo Blue Gum",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 640,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_samba_og_white_halo_blue_gum.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Stan Smith White Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 390,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_stan_smith_white_black.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas superstar Mauve",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 490,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_superstar_mauve.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Samba Valentine’s Day 2024",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 700,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_samba_valentine_s_day_2024.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Yeezy 700 V3 Alvah",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_yeezy_700_v3_alvah.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Yeezy Boost 350 V2 Mono Ice",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 710,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_yeezy_boost_350_v2_mono_ice.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "On Cloudtilt x Loewe All Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 690,
        category: catMap["sneakers"],
        brand: "On",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_on_cloudtilt_x_loewe_all_black.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Dior B25 Black Oblique",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 1950,
        category: catMap["sneakers"],
        brand: "Autre",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_dior_b25_black_oblique.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Dunk Low Off-White Lot 50",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_dunk_low_off_white_lot_50.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Max 95 x Worksout Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 690,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_max_95_x_worksout_black.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Force 1 ’07 Triple Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 490,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_force_1__07_triple_black.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Hermes Izmir sandal Black",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 1660,
        category: catMap["sneakers"],
        brand: "Autre",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_hermes_izmir_sandal_black.png"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 4 Metallic Purple",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 630,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_4_metallic_purple.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Nike Air Jordan 1 Retro Low OG SP Travis Scott Triple White",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 680,
        category: catMap["sneakers"],
        brand: "Nike",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_nike_air_jordan_1_retro_low_og_sp_travis_scott_triple_white.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas Niteball 2.0 Ecru Tint",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 520,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_niteball_2_0_ecru_tint.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Prada Cloudbust Thunder Knit White",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 740,
        category: catMap["sneakers"],
        brand: "Autre",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_prada_cloudbust_thunder_knit_white.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "New Balance 530 Triple White",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 650,
        category: catMap["sneakers"],
        brand: "New Balance",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_new_balance_530_triple_white.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      },
      {
        name: "Adidas SuperStar Cloud White",
        description: "Qualité Premium 1:1, détails authentiques garantis.",
        price: 600,
        category: catMap["sneakers"],
        brand: "Adidas",
        sizes: [38, 39, 40, 41, 42, 43, 44, 45],
        images: ["https://solestyle-ecommerce-production.up.railway.app/uploads/itsu_adidas_superstar_cloud_white.jpg"],
        stock: 50, rating: 4.9, reviewCount: Math.floor(Math.random() * 500) + 50, isFeatured: false,
      }
    ];

    const createdProducts = await Product.create(products);
    console.log(`👟 ${createdProducts.length} produits originaux créés (Itsu.ma clone) !`);

    console.log("\n✅ Base de données clonée avec succès !");
    process.exit(0);
  } catch (err) {
    console.error("❌ Erreur:", err.message);
    process.exit(1);
  }
}

seed();
